# Generated by Django 4.2.1 on 2023-05-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comment_text_alter_new_text_alter_new_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='generate',
            field=models.BooleanField(default=False),
        ),
    ]
